ports:
- port: 8001
  onOpen: open-preview
tasks:
- name: Terminal
  init: >
    composer install;
    mkdir datos;
    sed -i 's/AUTO_INCREMENT//; s/ENGINE=InnoDB DEFAULT CHARSET=utf8//' sql.esquema.txt
    sqlite3 datos/basededatos.sqlite < sql.esquema.txt
    sqlite3 datos/basededatos.sqlite < sql.datos.txt
    echo '<?php self::$configuracion['dsn'] = "sqlite:'$(realpath datos/basededatos.sqlite)'";' > src/configuracion.php
  command: >
    clear;
    echo "";
    echo "Cosas que puedes hacer en este terminal:";
    echo " * apachectl stop";
    echo " * apachectl start";
    echo " * gp open /var/log/apache2/access.log";
    echo " * gp open /var/log/apache2/error.log";
- name: Apache
  command: >
    apachectl start &&
    multitail /var/log/apache2/access.log -I /var/log/apache2/error.log