language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - nightly
service:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE asc;'
  - mysql asc < sql.esquema.txt
  - mysql asc < sql.datos.txt
install:
  - composer install

