language: php
php:
#  - '5.6'
#  - '7.0'
#  - '7.1'
#  - '7.2'
#  - '7.3'
  - nightly
service:
  - mysql
before_install:
  - mysql -u root -e 'CREATE DATABASE `asc`;'
  - mysql -u root asc < sql.esquema.txt
  - mysql -u roor asc < sql.datos.txt
install:
  - composer install

